### ISSUE TITLE
New visitors targeting with server side implementation

### ISSUE THREAD

**Issue by bbuhler** [adobe/target-nodejs-sdk#18]
Hello,
I hope this is the right place for my questions.

While running an AB test using the Adobe Target NodeJS SDK, we noticed that the numbers of new visitors in reports are much higher than usual (with client side implementation) and than our own visitors tracking.

Target shows a total of 842,997 new visitors during the period whereas our tracking shows 24,954 new (of 80.394 total / 66,244 unique) visitors for example. 

So I'm wondering if we might miss something in our server side implementation that helps to identify new visitors.

<details>
<summary>Here is our server side implementation</summary>

```javascript
import TargetClient from '@adobe/target-nodejs-sdk';

const enableTargetCookie = process.env.NODE_ENV === 'production';

const convertMboxes = mboxes => mboxes.reduce((acc, cur) => (cur.options ? { [cur.name]: cur.options[0].content, ...acc } : acc), {});
const convertPageLoadOptions = options => options && options.map(option => option.content).reduce((acc, cur) => [...acc, ...cur]);

export default function (mboxes, config)
{
  const targetClient = TargetClient.create(config);

  return async function (req, res, next)
  {
    if (req.hostname !== 'localhost')
    {
      const targetCookie = enableTargetCookie ? req.cookies[TargetClient.TargetCookieName] : undefined;
      const targetLocationHintCookie = enableTargetCookie ? req.cookies[TargetClient.TargetLocationHintCookieName] : undefined;

      const address = { url: req.hostname + req.originalUrl };
      const request = {
        context:
        {
          channel: 'web',
          browser: { host: req.hostname },
        },
        execute:
        {
          pageLoad: { address },
          mboxes: mboxes.map(name => ({ address, name })),
        },
      };

      if (req.query.at_preview_token)
      {
        const {
          at_preview_token,
          at_preview_index,
          at_preview_listed_activities_only,
          at_preview_evaluate_as_true_audience_ids,
          at_preview_evaluate_as_false_audience_ids,
        } = req.query;
        const [ activityIndex, experienceIndex ] = at_preview_index.split('_').map(index => parseInt(index));
        const audienceIds = ids => ids ? Array.isArray(ids) ? ids.map(id => parseInt(id)) : [parseInt(ids)] : undefined;

        request.qaMode = {
          token: at_preview_token,
          listedActivitiesOnly: at_preview_listed_activities_only === 'true',
          evaluateAsTrueAudienceIds: audienceIds(at_preview_evaluate_as_true_audience_ids),
          evaluateAsFalseAudienceIds: audienceIds(at_preview_evaluate_as_false_audience_ids),
          previewIndexes: [
            { activityIndex, experienceIndex },
          ],
        };
      }

      const response = await targetClient.getOffers({ request, targetCookie, targetLocationHintCookie });
      const execute = response.response.execute;

      const hasModifications = execute.mboxes.some(mbox => mbox.options) || execute.pageLoad.options;

      if (hasModifications)
      {
        req.adobeTarget = {
          mboxes: convertMboxes(execute.mboxes),
          pageLoad: convertPageLoadOptions(execute.pageLoad.options),
        };

        if (enableTargetCookie)
        {
          const setCookie = cookie => res.cookie(cookie.name, cookie.value, { maxAge: cookie.maxAge * 1000 });

          setCookie(response.targetCookie);
          setCookie(response.targetLocationHintCookie);
        }
      }
    }

    next();
  }
}

```

```javascript
    import adobeTarget from './middlewares/adobeTarget.js';

    ...
    .use(/.+\/(fr)?$/, adobeTarget(['runway:atf'],
      {
        logger,
        client: '...',
        organizationId: '...',
      }))
```

The `req.adobeTarget` object is later used in server side rendering processes.
</details>

---

In your examples repository I found the [ecid-integration](https://github.com/adobe/target-nodejs-sdk-samples/tree/master/ecid-integration) example.

Is it required to have a client side `VisitorAPI.js` / ECID implementation to have the visitors tracking working correctly?

Kind regards,
Ben

**Comment by jasonwaters** [comment]
Hi @bbuhler,

Do you use A4T reporting or target reporting?  If A4T, you definitely need to use VisitorAPI.js in the browser. Then parse the `VisitorCookie` and send it in the getOffers call.

One other thing i noticed in your code is the use of `targetLocationHintCookie`.  If you are using the latest version of the SDK (2.x) this has been renamed to just `targetLocationHint` and is a string value.

**Comment by bbuhler** [comment]
Hi @jasonwaters, thanks for your answer.

I'm not sure but I think it's target reporting. How can I identify which is been used?

We are still on version 1.1.0. I will keep it in mind when we update the package, thank you.

**Comment by jasonwaters** [comment]
Hi @bbuhler , please open a support ticket [here](https://experienceleague.adobe.com/?lang=en&support-solution=General#support) and our support team can get someone to help resolve this issue.

**Comment by bbuhler** [comment]
We will do that, thanks so far (:
