### ISSUE TITLE
Proxy Configuration

### ISSUE THREAD

**Issue by ridi-mz** [adobe/target-nodejs-sdk#28]
Hello, 
My application requires a proxy. I couldn't find a way to configure a proxy in the nodejs sdk. Any help ?

**Comment by jasonwaters** [comment]
Hi @ridi-mz ,

The node SDK (latest version) allows you to override which fetch implementation is used using the `fetchApi` configuration option.  By default, [node-fetch](https://github.com/node-fetch/node-fetch) is used.  But you can pass in a custom function instead that sets up a proxy for all fetch calls.  

This sample code may be useful for you ➡️ https://github.com/adobe/target-nodejs-sdk/blob/main/packages/target-nodejs-sdk/demo/demo.js#L6
