### ISSUE TITLE
QAmode for get-offers call

### ISSUE THREAD

**Issue by andrei-svistunou** [adobe/target-nodejs-sdk#30]
Hi all,

I'd like to ask about NodeJS SDK https://adobetarget-sdks.gitbook.io/docs/sdk-reference-guides/nodejs-sdk/get-offers
I can't find the property field `QAmode`, but I can find this property for Java SDK simultaneously.  

I we look into NodeJS, the type definition for QAmode is presented https://github.com/adobe/target-nodejs-sdk/blob/46c378b17a6533fa93b6652daed0d09a6be35b61/packages/target-tools/delivery-api-client/models/QAMode.d.ts 

Is it a mistake and we can wait for the fix in the next version? Or it's a permanent solution to skip QAmode at all

Thank you.

**Comment by jasonwaters** [comment]
Hi @andrei-svistunou, QAMode is supported in the NodeJS sdk.  It can be used by passing in a qaMode object as described in the [Delivery API documentation](https://developers.adobetarget.com/api/delivery-api/).

Here is an example:

```javascript
const client = TargetClient.create({
        client: "myAdobeClientId",
        organizationId: "ABCDEFG@AdobeOrg"
});


const result = await client.getOffers({
              request: {
                id: {
                  tntId: "338e3c1e51f7416a8e1ccba4f81acea0.28_0"
                },
                context: {
                  channel: "web"
                },
                prefetch: {
                  mboxes: [{ index: 0, name: "demo-marketing-offer1" }]
                },
                qaMode: {
                  token: "QCfbJvlzWVIdSjvDOUtz+J7srqQZYj1dadvKwaf8yb8=",
                  listedActivitiesOnly: true,
                  previewIndexes: [
                    {
                      activityIndex: 1,
                      experienceIndex: 2
                    }
                  ]
                }
              }
            });
```

Using QA mode, this request always returns experience 2 for the activity.
