### ISSUE TITLE
Does target-nodejs-sdk supports IPv6 address for IP based geo lookup?

### ISSUE THREAD

**Issue by saikiran11** [adobe/target-nodejs-sdk#44]
I am trying to implement Adobe Target server side implementation using target-node-sdk v2.1.3. I am using X-Forwarded-For header to get end user IP address and passing that value in the geo object of Target request but getting Bad request response. when I see logs I found IPv6 address is being sent to the Target request.  Does target-node-sdk supports IPv6 based geo lookup?

**Comment by XDex** [comment]
@saikiran11 Currently IPv6 addresses are not supported in Target, though we do have plans on adding support in the near future. Please follow the changelog and future release notes for further updates on IPv6 support.
